from __future__ import annotations

import pandas as pd
import pytest

pytest.importorskip(
    "hypothesis",
    reason="Hypothesis is declared in the locked test dependencies but is not installed locally",
)
from hypothesis import given, settings  # noqa: E402
from hypothesis import strategies as st

from forecast_longterm.wavelet_optimization.snapshots import CoverageLedger

_COVERAGE_STATUSES = ("complete", "incomplete", "missing", "invalid")
_SCOREABILITY_BY_STATUS = {
    "complete": "scoreable",
    "incomplete": "not_scoreable_coverage_incomplete",
    "missing": "not_scoreable_source_missing",
    "invalid": "not_scoreable_snapshot_invalid",
}
_COVERAGE_COLUMNS = (
    "source_id",
    "origin_date",
    "horizon_months",
    "snapshot_manifest",
    "source_vintage",
    "available_through",
    "sha256",
    "n_observations_available",
    "n_missing",
    "coverage_status",
    "scoreability_status",
    "required_for_candidate",
    "excluded_origins",
    "reason",
)


@st.composite
def _coverage_cases(draw: st.DrawFn) -> tuple:
    source_numbers = draw(
        st.lists(
            st.integers(min_value=0, max_value=100),
            min_size=2,
            max_size=3,
            unique=True,
        )
    )
    origin_offsets = draw(
        st.lists(
            st.integers(min_value=0, max_value=120),
            min_size=2,
            max_size=3,
            unique=True,
        )
    )
    horizons = draw(
        st.lists(
            st.sampled_from((6, 12)),
            min_size=1,
            max_size=2,
            unique=True,
        )
    )

    combination_count = len(source_numbers) * len(origin_offsets) * len(horizons)
    status_tail = draw(
        st.lists(
            st.sampled_from(_COVERAGE_STATUSES),
            min_size=combination_count - len(_COVERAGE_STATUSES),
            max_size=combination_count - len(_COVERAGE_STATUSES),
        )
    )
    statuses = tuple(_COVERAGE_STATUSES) + tuple(status_tail)

    exclusion_tail = draw(
        st.lists(
            st.booleans(),
            min_size=combination_count - 4,
            max_size=combination_count - 4,
        )
    )
    # Force coverage of both the non-excluded complete path and the exclusion
    # path while keeping the remaining exclusion pattern generated by Hypothesis.
    exclusions = (False, True, True, True) + tuple(exclusion_tail)
    predictive_r2 = draw(
        st.floats(
            min_value=-10.0,
            max_value=10.0,
            allow_nan=False,
            allow_infinity=False,
        )
    )
    return source_numbers, origin_offsets, tuple(horizons), statuses, exclusions, predictive_r2


# Feature: long-horizon-wavelet-optimization, Property 5: Ledger de cobertura conserva ausencia separada del desempeño
# Validates: Requirements 5.4, 5.5
@settings(max_examples=10, deadline=None)
@given(case=_coverage_cases())
def test_coverage_ledger_keeps_missing_coverage_separate_from_performance(case: tuple) -> None:
    (
        source_numbers,
        origin_offsets,
        horizons,
        statuses,
        exclusions,
        predictive_r2,
    ) = case
    origins = tuple(
        pd.Timestamp("2010-01-01") + pd.DateOffset(months=offset)
        for offset in origin_offsets
    )
    sources = tuple(f"source_{number}" for number in source_numbers)
    combinations = [
        (source_id, origin, horizon)
        for source_id in sources
        for origin in origins
        for horizon in horizons
    ]
    assert len(combinations) == len(statuses) == len(exclusions)

    ledger = CoverageLedger(default_horizons=horizons)
    expected: dict[tuple[str, str, int], dict[str, object]] = {}

    for index, (source_id, origin, horizon) in enumerate(combinations):
        status = statuses[index]
        scoreability_status = _SCOREABILITY_BY_STATUS[status]
        reason = None if status == "complete" else f"generated_{status}"
        is_excluded = bool(exclusions[index]) and status != "complete"
        if is_excluded:
            reason = reason or "generated_exclusion"
            ledger.record_exclusion(
                source_id=source_id,
                origin=origin,
                horizon_months=horizon,
                reason=reason,
                coverage_status=status,
                scoreability_status=scoreability_status,
                n_observations_available=0,
                n_missing=1,
            )
        else:
            ledger.record_coverage(
                source_id=source_id,
                origin=origin,
                horizon_months=horizon,
                reason=reason,
                coverage_status=status,
                scoreability_status=scoreability_status,
                n_observations_available=1 if status == "complete" else 0,
                n_missing=0 if status == "complete" else 1,
            )

        key = (source_id, origin.strftime("%Y-%m-%d"), horizon)
        expected[key] = {
            "coverage_status": status,
            "scoreability_status": scoreability_status,
            "reason": reason,
            "excluded": is_excluded,
        }

    # A predictive value is intentionally stored in the separate performance
    # channel; coverage serialization must not absorb it.
    first_source, first_origin, first_horizon = combinations[0]
    ledger.record_performance(
        origin=first_origin,
        horizon_months=first_horizon,
        candidate_id="generated_candidate",
        r2_oos=predictive_r2,
    )

    coverage_dicts = ledger.as_dicts()
    coverage_frame = ledger.to_frame()
    expected_keys = set(expected)
    serialized_keys = {
        (row["source_id"], row["origin_date"], row["horizon_months"])
        for row in coverage_dicts
    }
    frame_keys = {
        (row.source_id, str(row.origin_date), int(row.horizon_months))
        for row in coverage_frame.itertuples(index=False)
    }

    assert len(ledger.records) == len(expected_keys)
    assert len({record.key for record in ledger.records}) == len(expected_keys)
    assert len(coverage_dicts) == len(expected_keys)
    assert len(coverage_frame) == len(expected_keys)
    assert serialized_keys == expected_keys
    assert frame_keys == expected_keys
    assert list(coverage_frame.columns) == list(_COVERAGE_COLUMNS)
    assert all(set(row) == set(_COVERAGE_COLUMNS) for row in coverage_dicts)
    assert "r2_oos" not in coverage_frame.columns
    assert all("r2_oos" not in row for row in coverage_dicts)

    for row in coverage_dicts:
        key = (row["source_id"], row["origin_date"], row["horizon_months"])
        expected_row = expected[key]
        assert row["coverage_status"] == expected_row["coverage_status"]
        assert row["scoreability_status"] == expected_row["scoreability_status"]
        assert row["reason"] == expected_row["reason"]
        if expected_row["coverage_status"] != "complete":
            assert row["coverage_status"] in {"incomplete", "missing", "invalid"}
            assert row["scoreability_status"] != "scoreable"
            assert row["reason"]
        if expected_row["excluded"]:
            assert row["origin_date"] in row["excluded_origins"]

    assert ledger.performance_records[0]["r2_oos"] == predictive_r2
    assert "r2_oos" in ledger.performance_frame().columns
